### PR TITLE
Update config.yml

### PR DESCRIPTION
**Pull request by QuentinBisson**

### CODE REVIEW

**Comment by tomahawk28** [comment]
There was a validation error. 
```
main.go:110:15: G402: TLS MinVersion too low. (gosec)
		TLSConfig: &tls.Config{
			GetCertificate: cm.GetCertificate,
		},
```	
Which version is the minimum requirement for gosec?

**Comment by QuentinBisson** [comment]
TLS 1.2 should work: https://github.com/go-redis/redis/issues/1553

**Comment by tomahawk28** [comment]
let's rebase this PR after this https://github.com/giantswarm/app-admission-controller/pull/108

**Review by tomahawk28 — APPROVED** [review]
LGTM when CI reports green.

**Pull request merged**
