### PR TITLE
Adding v-prefix versions support

### PR DESCRIPTION
**Pull request by ljakimczuk**
## Checklist

- [x] Update changelog in CHANGELOG.md.

Related [issue](https://github.com/giantswarm/giantswarm/issues/19700).

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Review by rossf7 — APPROVED** [review]
LGTM when tested

Meta: Can you link to the issue in the PR desc for tracking?

**Comment by ljakimczuk** [comment]
> Meta: Can you link to the issue in the PR desc for tracking?

The issue? Which issue do you mean?

**Comment by rossf7** [comment]
> Which issue do you mean?

I think https://github.com/giantswarm/giantswarm/issues/19700 is fine. Since its the dog fooding that found that we needed this.

**Comment by ljakimczuk** [comment]
@rossf7 sure, makes sense, thanks!

**Review by rossf7 — APPROVED** [review]

**Pull request merged**
