### PR TITLE
Delete unnecessary deletion timestamp check

### PR DESCRIPTION
**Pull request by kopiczko**
Towards https://github.com/giantswarm/giantswarm/issues/14993

We already have this (below) specified in the webhook configurations so
delete events are not dispatched to the mutator/validator.

        operations:
          - CREATE
          - UPDATE

### CODE REVIEW

**Review by JosephSalisbury — APPROVED** [review]
lgtmiiwfy

**Review by rossf7 — CHANGES_REQUESTED** [review]
For ~tenant~ workload clusters we delete the cluster namespace rather than the app CRs individually.

So the admission controller needs to handle the update event by checking for the deletion timestamp.

**Comment by kopiczko** [comment]
Do you mean App CR being updated after being scheduled for deletion?

**Comment by rossf7** [comment]
> Do you mean App CR being updated after being scheduled for deletion?

The problem is because the cluster values configmap and the kubeconfig secret are deleted first because they have no finalizer. For the app CRs there is an update event to set the deletion timestamp but the validation fails because the resources now do not exist.

The current code allows the update to take place and means the app CRs are deleted cleanly.

**Review by rossf7 — COMMENTED** [review]
@kopiczko I think this will work and simplifies things but I'd like to test it with a TC.

I'll do that tomorrow as I'm mostly AFK today. Currently testing is a bit hard because it needs a release with app-operator 3.0.0.

**Comment by kopiczko** [comment]
I tested that in my local setup and you are right. To repro:

- I created an app in in a namespace
- Added finalizer to the app
- Deleted the namespace
- Edited the app manually
- There was an event for the app with the deletion timesamp (setting the deletion timestamp itself didin't trigger the event)

**Pull request closed without merging**
